### PR TITLE
Add usual settings & integrations

### PR DESCRIPTION
**Pull request by skalee**
Gitignore, Rubocop, Hound, and README in AsciiDoc.

### CODE REVIEW

**Comment by skalee** [comment]
@ronaldtse As far as I can see, here we're using CodeClimate instead of Hound, right? And it also checks style against Rubocop config file.

**Comment by skalee** [comment]
Also, supporting Ruby 2.2+ and Rails 4+ is fine, isn't it?

**Comment by ronaldtse** [comment]
I just enabled Hound for this. Yes indeed what you mentioned is good. Thanks!

**Comment by skalee** [comment]
@ronaldtse Pls enable Travis as well, thanks in advance!

**Pull request merged**
