### PR TITLE
Remove irrelevant parameter constraints on authenticity_token parameter

### PR DESCRIPTION
**Pull request by skalee**
Request parameters should be constrained with some other tools, for instance Rails routes or https://rubygems.org/gems/stronger_parameters gem.

### CODE REVIEW

**Comment by skalee** [comment]
@ronaldtse I want to confirm that it's okay to remove parameter length limiter and checks on `authenticity_token` from the Rack-Cleanse since IMHO this can be better done with Strong Parameters gem. Please merge if yes.

**Comment by skalee** [comment]
Fixes #23 (by removing non-thread-safe parts).

**Comment by ronaldtse** [comment]
@skalee we should indeed remove the authentication_token part, but I think we should have some reasonable limit of parameter length as an earlier gate in Rack prior to such parameters hitting Rails.

**Comment by skalee** [comment]
Hmm okay… Any benefit for long parameters not reaching Rails router? Cause in controllers, length limits can be imposed with Stronger Parameters gem. And I mean both their [byte length](https://github.com/zendesk/stronger_parameters/blob/b6566d009df2a6bdddca149b9b1fa012394e20d2/lib/stronger_parameters/constraints/string_constraint.rb#L9-L10) or the maximum number of characters (via regular expressions).

**Comment by ronaldtse** [comment]
Rails often break in multiple ways so it's just one global place to set a real maximum. I meant the total length of the URI, not a per parameter limitation.

**Comment by skalee** [comment]
Agreed.

**Comment by ronaldtse** [comment]
Thanks @skalee !

**Comment by skalee** [comment]
I've removed my commits related to the parameter length cleanser. Also, #23 is not fixed (issue is strictly bound with that cleanser).

**Comment by skalee** [comment]
Renamed a pull request title to better match what I eventually did here.

**Pull request merged**
